oauth2:
  prefix: Bearer
  type: application/json
  github:
    client-id: 6ed445436a1a391574c4
    client-secret: 9ea0190cb2dea6b746b0dcdaa69aee00bc9b683d
    base-url: https://api.github.com
    access-token-url: https://github.com/login/oauth/access_token
    information-url: https://api.github.com/user
    email-url: https://api.github.com/user/emails